spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/myDB_managerCH
    username: han
    password: han

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081

ftp:
  ipServer: 192.168.100.5
  user: test
  pass: 1234